# Generated by Django 4.2.8 on 2026-01-21 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, help_text="The client's IP address (IPv4 or IPv6)", max_length=45, validators=[django.core.validators.validate_ipv46_address])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The time the request was received')),
                ('path', models.CharField(db_index=True, help_text='The URL path that was requested', max_length=2048)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='ip_tracking_ip_addr_f0dbdd_idx'), models.Index(fields=['path', '-timestamp'], name='ip_tracking_path_febde3_idx')],
            },
        ),
    ]
