# Generated by Django 4.2.8 on 2026-01-21 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, help_text='The IP address to block (IPv4 or IPv6)', max_length=45, unique=True, validators=[django.core.validators.validate_ipv46_address])),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='When the IP was added to the blacklist')),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking this IP')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
