# Generated by Django 4.2.8 on 2026-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='The city where the request originated', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='The country where the request originated', max_length=100, null=True),
        ),
    ]
