# Generated by Django 4.2.8 on 2026-01-21 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, help_text='The suspicious IP address', max_length=45, validators=[django.core.validators.validate_ipv46_address])),
                ('reason', models.CharField(choices=[('high_requests', 'High number of requests'), ('admin_access', 'Attempted admin access'), ('login_access', 'Attempted login access'), ('pattern_match', 'Suspicious pattern detected'), ('other', 'Other suspicious activity')], default='other', help_text='Reason for flagging as suspicious', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the suspicious activity was detected')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests in the suspicious time window')),
                ('is_investigated', models.BooleanField(db_index=True, default=False, help_text='Whether the anomaly has been investigated')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the anomaly')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['ip_address', '-detected_at'], name='ip_tracking_ip_addr_3dac06_idx'), models.Index(fields=['is_investigated', '-detected_at'], name='ip_tracking_is_inve_d3501a_idx')],
            },
        ),
    ]
